name: 'Terraform CI/CD'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  TF_VERSION: '1.7.4'
  AZURE_PROVIDER_VERSION: '~> 3.80.0'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Set up Terraform
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Login to Azure
      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
         
      # Initialize Terraform configuration
      - name: 'Terraform Init'
        run: terraform init

      # Validate the Terraform configuration
      - name: 'Terraform Validate'
        run: terraform validate

      # Run Terraform Plan to generate execution plan
      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan

      # Apply the Terraform plan
      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
