name: 'Terraform CI/CD'
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
env:
  TF_VERSION: '1.7.4'
  AZURE_PROVIDER_VERSION: '~> 3.80.0'
 
jobs:
  terraform:
    name: 'Terraform Plan Only'
    runs-on: ubuntu-latest
 
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
 
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
 
      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
 
      - name: 'Terraform Init'
        run: terraform init
 
      - name: 'Terraform Validate'
        run: terraform validate
 
      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan

      - name: 'Terraform apply'
        run: terraform apply tfplan
